name: Deploy

env:
  # UPGRADE: Change version here when upgrading 
  PUBLISH_DIR: src/Expanse.Web/bin/Release/net6.0/publish/wwwroot
  CONTENT_BASE: /Expanse/

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        # UPGRADE: Change version here when upgrading
        dotnet-version: 6.0.x
    - name: Publish application
      run: dotnet publish -c Release
    - name: Rewrite base href
      if: success()
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: ${{ env.CONTENT_BASE }}
    - name: Add .nojekyll file
      run: touch ${{ env.PUBLISH_DIR }}/.nojekyll
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
